In [ ]:
import pandas as pd
import numpy as np

file_path = "../../data/raw/Analise_LongNeck_WSNP - Sem repostas.xlsb"
xls = pd.ExcelFile(file_path)

df = pd.read_excel(xls, sheet_name="Custos de transferência", header=None, engine="pyxlsb")

df_data = df.iloc[:, :]
df_data

,0,1,2,3,4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,Custo de Transferências,NaN,NaN,NaN
2,NaN,SKU,Origem,Destino,Reais / HL
3,NaN,COLORADO LAGER LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,76.592891
4,NaN,COLORADO LAGER LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,82.07998
5,NaN,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,82.395382
6,NaN,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,BR23 - F. JAGUARIUNA - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,84.579425
7,NaN,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,88.29816
8,NaN,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,BR23 - F. JAGUARIUNA - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,95.328283
9,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN
11,NaN,MACOs - Produção Interna,NaN,NaN,NaN
12,NaN,SKU,NaN,NaN,Reais / HL
13,NaN,COLORADO LAGER LN 355ML CX C/12,NaN,NaN,300
14,NaN,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,350
15,NaN,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,BR16 - F. JACAREI - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,285
16,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN
18,NaN,Custo de Produção,NaN,NaN,NaN
19,NaN,SKU,NaN,NaN,Reais / HL
20,NaN,COLORADO LAGER LN 355ML CX C/12,NaN,NaN,150
21,NaN,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,155
22,NaN,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,BR16 - F. JACAREI - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,149

In [8]:
df_transf = df.iloc[3:9, 1:5].copy()
df_transf.columns = ["SKU", "Origem", "Destino", "Reais_por_HL"]
df_transf.reset_index(drop=True, inplace=True)
df_transf["Reais_por_HL"] = df_transf["Reais_por_HL"].astype(float)

print("=== CUSTO DE TRANSFERÊNCIAS ===")
df_transf

=== CUSTO DE TRANSFERÊNCIAS ===

,SKU,Origem,Destino,Reais_por_HL
0,COLORADO LAGER LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,76.592891
1,COLORADO LAGER LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,82.079980
2,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,82.395382
3,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,BR23 - F. JAGUARIUNA - PLANT - SP,BR04 - F. CAMACARI - PLANT - BA,84.579425
4,GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12,BR16 - F. JACAREI - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,88.298160
5,MALZBIER BRAHMA LN355ML SIX PAC BAND C/4,BR23 - F. JAGUARIUNA - PLANT - SP,BR06 - F. FONTE MATA - RDC - PB,95.328283

In [9]:
df_macos = df.iloc[13:16, [1,4]].copy()
df_macos.columns = ["SKU", "Reais_por_HL"]
df_macos.reset_index(drop=True, inplace=True)
df_macos["Reais_por_HL"] = df_macos["Reais_por_HL"].astype(float)

print("=== MACOs - PRODUÇÃO INTERNA ===")
df_macos

=== MACOs - PRODUÇÃO INTERNA ===

                                        SKU  Reais_por_HL
0           COLORADO LAGER LN 355ML CX C/12         300.0
1  GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12         350.0
2  MALZBIER BRAHMA LN355ML SIX PAC BAND C/4         285.0

In [11]:
df_producao = df.iloc[20:23, [1,4]].copy()
df_producao.columns = ["SKU", "Reais_por_HL"]
df_producao.reset_index(drop=True, inplace=True)
df_producao["Reais_por_HL"] = df_producao["Reais_por_HL"].astype(float)

print("=== CUSTO DE PRODUÇÃO ===")
df_producao

=== CUSTO DE PRODUÇÃO ===

                                        SKU  Reais_por_HL
0           COLORADO LAGER LN 355ML CX C/12         150.0
1  GOOSE ISLAND MIDWAY NAC LN 355ML CX C/12         155.0
2  MALZBIER BRAHMA LN355ML SIX PAC BAND C/4         149.0

In [ ]:
#Custo por Hl de MalzBier